name: CD

on:
  push:
    branches:
      - main
    paths:
      - 'packages/admin/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      # caching
      - name: Cache Yarn dependencies
        uses: actions/cache@v2
        id: cache-primes
        with:
          path: packages/admin/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('packages/admin/yarn.lock') }}

      # only install if there is no cache
      - name: Install dependencies
        if: steps.cache-primes.outputs.cache-hit != 'true'
        run: yarn --cwd packages/admin

      - name: Build project
        run: yarn --cwd packages/admin build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to S3
        run: aws s3 sync packages/admin/out s3://admin.elasticwebdev.com
